## Introducción a la biblioteca NUMPY - TLP3 - Python para CD

NumPy es una biblioteca fundamental para el lenguaje Python, diseñada para el cálculo numérico y el manejo eficiente de arreglos y matrices multidimensionales. 

**Importaciones**

Para poder utilizar numpy debemos instalarlo con pip dentro de nuestro entorno virtual. Una vez importado, por convención utilizaremos como alias **"np"**.

In [1]:
import numpy as np

**Creación de arreglos**: Numpy permite crear arreglos a partir de listas, tuplas y otros objetos iterables, así como generar arreglos con valores específicos (ceros, unos, secuencias). Las listas convertidas con el metodo array(lista) de numpy, pasan a ser automaticamente objectos de numpy.

In [8]:

lista = [1,2,3,4,5]
lista_dos = [6,7,8,9,10]

arr = np.array(lista)
arr_dos = np.array(lista_dos)
print(arr)
print(arr_dos)

print(type(arr))
print(type(arr_dos))

[1 2 3 4 5]
[ 6  7  8  9 10]
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


La variable **lista_uno** y **lista_dos** se convirtieron en objetos de la clase **numpy**, ahora del tipo **“ndarray”**, esto significa que ahora es un array de N dimensiones.

### Operaciones aritméticas. 

**Sumas de arreglos:** Para la suma de arreglos podemos utilizar el operador “+” o  utilizar la función “add()” de numpy.

In [9]:
# Sumar listas
suma = np.add(lista, lista_dos)
print(suma)

[ 7  9 11 13 15]


**Resta de arreglos:** para la resta de arreglos podemos utilizar el operador ‘ - ’ o también con el metodo de la clase numpy ‘subtract()’.

In [15]:
#Restas

resta = np.subtract(arr_dos, arr)
print(resta)

[5 5 5 5 5]


**Multiplicación de arreglos:** Con numpy podemos multiplicar arreglos de forma muy sencilla, simplemente usando la función multiply o el operador “*”.

In [11]:
#Multiplicación 

multi = np.multiply(arr, arr_dos)
print(multi)

[ 6 14 24 36 50]


**División de arreglos con numpy:** La función "divide()" y el operador "/" simplifican la división de arreglos con numpy.

In [17]:
division = np.divide(arr_dos, arr)
print(division)

condicion = arr < 3
print(arr[condicion])

[6.         3.5        2.66666667 2.25       2.        ]
[1 2]


### Creación de Arreglos
Los **arreglos**, también llamados matrices, son estructuras de datos fundamentales para almacenar y manipular datos numéricos en una amplia gama de aplicaciones científicas y de ingeniería. En Python, la función **"array()"** se usa comúnmente para crear arreglos; sin embargo, existen otras funciones disponibles para este propósito.


1. *arange:* Genera un arreglo con valores espaciados uniformemente dentro de un rango especificado. Recibe como parámetro el inicio, límite (no incluido) y el espacio entre elementos (pasos).

In [ ]:
np.arange(0, 10, 2) # ! inicio, fin, salto

array([0, 2, 4, 6, 8])

 2. *`linspace`*: Similar a `arange`, pero especifica el número de elementos en lugar del espaciado. Recibe como parámetro el inicio, límite(incluido) y la cantidad de elementos entre estos dos.

In [44]:
np.linspace(1, 20, 5) # ! inicio, fin, cantidad de elementos

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])


3. `zeros`: Crea un arreglo lleno de ceros con la forma deseada. Recibe como parámetros shape (forma del arreglo / dimensiones) y dtype (tipo de valores, por defecto ‘float’).

In [45]:
np.zeros((4,3), dtype=int) # ! filas, columnas y tipo de valor

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

4. `ones`: Crea un arreglo lleno de unos con la forma deseada.Recibe como parámetros shape (forma del arreglo / dimensiones) y dtype (tipo de valores, por defecto ‘float’).

In [ ]:
np.ones((2,3), dtype=int) # ! filas, columnas y tipo de valor

array([[1, 1, 1],
       [1, 1, 1]])

5.`empty`: Crea un arreglo sin inicializar los valores, lo que puede ser más rápido pero produce resultados impredecibles.

In [46]:
np.empty((2,2), dtype=int) # ! filas, columnas y tipo de valor

array([[4607182418800017408, 4616189618054758400],
       [4619567317775286272, 4621819117588971520]])

6. `eye`: Genera una matriz identidad con la diagonal principal llena de unos y el resto de ceros.
Parámetros:
N: Número de filas de la matriz.
M (opcional): Número de columnas de la matriz. Si no se especifica, M será igual a N, lo que crea una matriz cuadrada.
k (opcional): Desplazamiento de la diagonal.
Si k = 0, la diagonal principal tendrá los 1s.
Si k > 0, la diagonal será desplazada hacia arriba.
Si k < 0, la diagonal será desplazada hacia abajo.
dtype (opcional): Tipo de datos del arreglo resultante. El valor por defecto es float.


In [39]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

7. `diag`: Crea una matriz diagonal a partir de una lista de valores o extrae la diagonal de una matriz existente.
Parámetros:
v: Si es un vector, se convertirá en una matriz diagonal. Si es una matriz, se extraerán los elementos de la diagonal.
k (opcional): Es el índice de la diagonal a extraer o colocar.
Si k = 0, se trabaja con la diagonal principal.
Si k > 0, se trabaja con una diagonal por encima de la principal.
Si k < 0, se trabaja con una diagonal por debajo de la principal.


In [41]:
np.diag([4,8,9])

array([[4, 0, 0],
       [0, 8, 0],
       [0, 0, 9]])